In [7]:
np_array=np.array(['str',1,True])
np_array

array(['str', '1', 'True'], dtype='<U11')

In [8]:
py_list=[2,3,4]
py_list+py_list

[2, 3, 4, 2, 3, 4]

In [9]:
py_array=np.array([2,3,4])
py_array+py_array

array([4, 6, 8])

In [4]:
import numpy as np

height=[2.56,3.78,4.50,6.78,9.56]
height_array=np.array(height)

weight=[46.7,60.5,89.4,88.6,56.7]
weight_array=np.array(weight)

bmi=weight_array/height_array**2
print(bmi)
print(f"The bmi of the second person is {round(bmi[1],2)}")
print(f"The bmi of the 4th person is {round(bmi[3],2)}")
print(f"The person whose height greater than 5 bmi is {height_array[bmi>5]}")
print(f" The bmi greater than 4 are {bmi[bmi>4]}")

[7.12585449 4.23420397 4.41481481 1.927411   0.62039355]
The bmi of the second person is 4.23
The bmi of the 4th person is 1.93
The person whose height greater than 5 bmi is [2.56]
 The bmi greater than 4 are [7.12585449 4.23420397 4.41481481]


In [13]:
bmi>23

array([False, False, False, False, False])

In [21]:
light=bmi>5

In [22]:
bmi[light]

array([7.12585449])

In [20]:
bmi[bmi>3]

array([7.12585449, 4.23420397, 4.41481481])

In [23]:
type(bmi) #numpy.ndarray means n-dimensional array
#bmi and weight/height are one dimensional array

numpy.ndarray

In [17]:
np_2d=np.array([[3,4,5,6,7],
                [1,2,3,7,8],
                [5,6,6,7,10]
               ])
np_2d

array([[ 3,  4,  5,  6,  7],
       [ 1,  2,  3,  7,  8],
       [ 5,  6,  6,  7, 10]])

In [19]:
np_2d.shape #rows and columns

(3, 5)

In [30]:
print(np_2d[0][4])
print(np_2d[1][3])
np_2d[0][2]
np_2d[0,1]
np_2d[2,2]
np_2d[1,:] #or
np_2d[1][:]
print(f"Second person's only 2nd 3rd and 4th number {np_2d[1,1:4]}")
print(f"3rd person's only 4th and 5th number {np_2d[2][3:]}")
print(f"All person 's 3rd number{np_2d[:,2]}")
print(f"All person's 2nd and 3rd number {np_2d[:,1:3]}")


7
7
Second person's only 2nd 3rd and 4th number [2 3 7]
3rd person's only 4th and 5th number [ 7 10]
All person 's 3rd number[5 3 6]
All person's 2nd and 3rd number [[4 5]
 [2 3]
 [6 6]]


In [32]:
np_2d[0,2]

5

In [33]:
np_2d[:,1:3]


array([[4, 5],
       [2, 3]])

In [34]:
np_2d[1,:]

array([1, 2, 3, 7, 8])

In [35]:
np_2d[:,1]

array([4, 2])

In [36]:
np_2d[0,:]

array([3, 4, 5, 6, 7])

In [38]:
np_2d[:,0]

array([3, 1])

In [39]:
baseball=[
    [180,9.4],
    [120,4.5],
    [200,5.6],
    [169,6.7]
]
np_baseball=np.array(baseball)
print(np_baseball)

[[180.    9.4]
 [120.    4.5]
 [200.    5.6]
 [169.    6.7]]


In [40]:
print(type(np_baseball))

<class 'numpy.ndarray'>


In [41]:
np_baseball.shape

(4, 2)

In [44]:
np_weight=np_baseball[:,1]
print(np_weight)

[9.4 4.5 5.6 6.7]


In [47]:
# Print out the 4th row of np_baseball
print(np_baseball[3,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb=np_baseball[:,1]
print(np_weight_lb)
# Print out height of 2nd player
print(np_baseball[1,0])

#Print out the 25th person's weight
print(np_baseball[2,1])

[169.    6.7]
[9.4 4.5 5.6 6.7]
120.0
5.6


In [33]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * np.array([2,2])

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [49]:
np_mat+np.array([10,10])

array([[11, 12],
       [13, 14],
       [15, 16]])

In [50]:
np_mat+np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [54]:
np_array=np.array([[2,3,4.5],
                  [4,5,6.2],
                  [6,7,8.4]])
np_array

array([[2. , 3. , 4.5],
       [4. , 5. , 6.2],
       [6. , 7. , 8.4]])

In [55]:
conversion=np.array([0.0245,0.453592,1])
print(np_array*conversion)

[[0.049    1.360776 4.5     ]
 [0.098    2.26796  6.2     ]
 [0.147    3.175144 8.4     ]]


In [56]:
mean_age=np.mean(np_array[:,2])
print(mean_age)

6.366666666666667


In [59]:
median_age=np.median(np_array[:,2])
print(median_age)

6.2


In [60]:
sum=np.sum(np_array[:,1])
print(sum)

15.0


In [63]:
std=np.std(np_array[:,0])
print(round(std,2))

1.63


In [66]:
np.corrcoef(np_array[:,1],np_array[:,2])

array([[1.        , 0.99727178],
       [0.99727178, 1.        ]])

In [69]:
sorted_np=np.sort(np_array[:,0])
print(sorted_np)

[2. 4. 6.]


In [35]:
height=np.round(np.random.normal(1.45,0.20,50),2)
weight=np.round(np.random.normal(45.5,10,50),2)
np_city=np.column_stack((height,weight))
print(np_city)

[[ 1.34 37.85]
 [ 1.47 42.82]
 [ 1.39 37.75]
 [ 1.41 59.56]
 [ 1.5  52.06]
 [ 1.25 47.19]
 [ 1.63 43.39]
 [ 1.76 32.94]
 [ 1.72 46.41]
 [ 1.15 43.27]
 [ 1.77 39.79]
 [ 1.45 44.51]
 [ 1.33 60.66]
 [ 1.49 33.35]
 [ 1.32 36.82]
 [ 1.84 63.91]
 [ 1.35 48.14]
 [ 1.63 59.48]
 [ 1.49 44.82]
 [ 1.32 31.74]
 [ 1.24 58.67]
 [ 1.45 56.24]
 [ 1.23 58.38]
 [ 1.52 29.83]
 [ 1.22 36.97]
 [ 1.2  46.98]
 [ 1.88 59.52]
 [ 1.78 48.53]
 [ 1.41 41.31]
 [ 1.64 43.25]
 [ 1.46 42.76]
 [ 1.51 58.7 ]
 [ 1.18 48.24]
 [ 1.88 43.49]
 [ 1.39 51.93]
 [ 1.47 62.79]
 [ 1.53 59.27]
 [ 1.57 40.29]
 [ 1.44 62.17]
 [ 1.32 49.32]
 [ 1.3  57.17]
 [ 1.41 64.17]
 [ 1.29 42.94]
 [ 1.62 35.19]
 [ 1.62 52.15]
 [ 1.34 52.77]
 [ 1.28 49.09]
 [ 1.7  38.37]
 [ 1.25 28.81]
 [ 1.52 45.2 ]]


In [75]:
mean_h=round(np.mean(np_city[:,0]),1)
mean_w=round(np.mean(np_city[:,1]),1)
print(mean_h)
print(mean_w)

1.4
45.2


In [76]:
std_h=round(np.std(np_city[:,0]),1)
std_w=round(np.std(np_city[:,1]),1)
print(std_h)
print(std_w)

0.2
9.0


In [78]:
np.corrcoef(np_city[:,0],np_city[:,1])

array([[ 1.        , -0.09525845],
       [-0.09525845,  1.        ]])

In [44]:
#sorted_city=sorted(np_city,key= lambda x:x[0])
sorted_city=np.sort(np_city)

print(sorted_city)

[[ 1.34 37.85]
 [ 1.47 42.82]
 [ 1.39 37.75]
 [ 1.41 59.56]
 [ 1.5  52.06]
 [ 1.25 47.19]
 [ 1.63 43.39]
 [ 1.76 32.94]
 [ 1.72 46.41]
 [ 1.15 43.27]
 [ 1.77 39.79]
 [ 1.45 44.51]
 [ 1.33 60.66]
 [ 1.49 33.35]
 [ 1.32 36.82]
 [ 1.84 63.91]
 [ 1.35 48.14]
 [ 1.63 59.48]
 [ 1.49 44.82]
 [ 1.32 31.74]
 [ 1.24 58.67]
 [ 1.45 56.24]
 [ 1.23 58.38]
 [ 1.52 29.83]
 [ 1.22 36.97]
 [ 1.2  46.98]
 [ 1.88 59.52]
 [ 1.78 48.53]
 [ 1.41 41.31]
 [ 1.64 43.25]
 [ 1.46 42.76]
 [ 1.51 58.7 ]
 [ 1.18 48.24]
 [ 1.88 43.49]
 [ 1.39 51.93]
 [ 1.47 62.79]
 [ 1.53 59.27]
 [ 1.57 40.29]
 [ 1.44 62.17]
 [ 1.32 49.32]
 [ 1.3  57.17]
 [ 1.41 64.17]
 [ 1.29 42.94]
 [ 1.62 35.19]
 [ 1.62 52.15]
 [ 1.34 52.77]
 [ 1.28 49.09]
 [ 1.7  38.37]
 [ 1.25 28.81]
 [ 1.52 45.2 ]]


In [38]:
sorted_w=np.sort(np_city[:,1])
sorted_baseball=np.column_stack((sorted_h,sorted_w))
print(sorted_w)

[28.81 29.83 31.74 32.94 33.35 35.19 36.82 36.97 37.75 37.85 38.37 39.79
 40.29 41.31 42.76 42.82 42.94 43.25 43.27 43.39 43.49 44.51 44.82 45.2
 46.41 46.98 47.19 48.14 48.24 48.53 49.09 49.32 51.93 52.06 52.15 52.77
 56.24 57.17 58.38 58.67 58.7  59.27 59.48 59.52 59.56 60.66 62.17 62.79
 63.91 64.17]


In [83]:
a=np.random.normal(1.3,0.3,20)
b=np.random.normal(1.2,0.2,20)
a_b=np.column_stack((a,b))
print(a_b)

[[1.53355092 1.19772323]
 [1.13061229 1.09246009]
 [1.40124372 1.07888782]
 [1.18756464 1.16987756]
 [1.18043458 1.03884001]
 [0.93286902 0.84149007]
 [1.6908764  1.17348272]
 [1.03309735 1.13954259]
 [1.38196903 1.24601853]
 [1.18000669 1.37831922]
 [0.92773976 0.93566662]
 [1.78361292 1.36822514]
 [1.32585138 1.23094549]
 [1.20471728 1.25629551]
 [1.44816623 1.15138144]
 [1.73632382 1.04133324]
 [1.14620041 1.04490266]
 [2.2770371  1.2586051 ]
 [1.43389539 1.21071935]
 [0.99145186 1.53821937]]


In [85]:
c=np.random.rand(20)
d=np.random.rand(20)
e=np.random.rand(20)
c_d_e=np.column_stack((c,d,e))
print(c_d_e)

[[0.39077159 0.23557547 0.73075188]
 [0.79308538 0.63486741 0.80310807]
 [0.34699625 0.25684857 0.59737567]
 [0.23638128 0.17439491 0.32036704]
 [0.14224548 0.21660388 0.26960773]
 [0.46480363 0.73612552 0.61441879]
 [0.99698782 0.7654716  0.46225838]
 [0.90020616 0.29393823 0.52941999]
 [0.36187989 0.30357011 0.38864989]
 [0.82143951 0.01839092 0.44299097]
 [0.23463889 0.75188793 0.67042867]
 [0.31721946 0.4850944  0.22377078]
 [0.32847535 0.78264366 0.6368399 ]
 [0.88324212 0.41123117 0.36508314]
 [0.14518786 0.05250411 0.15739843]
 [0.19334478 0.59436055 0.84476704]
 [0.85886516 0.01074273 0.63368996]
 [0.53421171 0.29381987 0.77339669]
 [0.37500536 0.29973422 0.07642946]
 [0.80565216 0.17174557 0.98883994]]


In [86]:
"""
Do big players tend to be heavier? 
Use np.corrcoef() to store the correlation between the first and second column of np_baseball in corr.
Replace None with the correct code.

# Import numpy
import numpy as np

np_heights
# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))
"""


'\nDo big players tend to be heavier? \nUse np.corrcoef() to store the correlation between the first and second column of np_baseball in corr.\nReplace None with the correct code.\n\n# Import numpy\nimport numpy as np\n\nnp_heights\n# Print mean height (first column)\navg = np.mean(np_baseball[:,0])\nprint("Average: " + str(avg))\n\n# Print median height. Replace \'None\'\nmed = np.median(np_baseball[:,0])\nprint("Median: " + str(med))\n\n# Print out the standard deviation on height. Replace \'None\'\nstddev = np.std(np_baseball[:,0])\nprint("Standard Deviation: " + str(stddev))\n\n# Print out correlation between first and second column. Replace \'None\'\ncorr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])\nprint("Correlation: " + str(corr))\n'

In [98]:
np_heights=np.round(np.random.normal(100.5,2.5,10))
positions=['GK','MK','FK','LK','GK','GK','MK','LK','GK','FK']
np_positions=np.array(positions)
gk_heights=np_heights[np_positions=='GK']
other_heights=np_heights[np_positions!='GK']

print(f"The median of the gk heights is {np.median(gk_heights)}")
print(f"The median of the other heights is {np.median(other_heights)}")

The median of the gk heights is 99.5
The median of the other heights is 99.0
