In [2]:
fam = [3, 4, 5, 67, 8, 9]
for index, h in enumerate(fam):
    print("index " + str(index) + " height: " + str(h))

index 0 height: 3
index 1 height: 4
index 2 height: 5
index 3 height: 67
index 4 height: 8
index 5 height: 9


In [3]:
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
for h in house:
    print("the "+h[0]+" is "+ str(h[1]) +" sqm.")

the hallway is 11.25 sqm.
the kitchen is 18.0 sqm.
the living room is 20.0 sqm.
the bedroom is 10.75 sqm.
the bathroom is 9.5 sqm.


In [4]:
#while loop
offset=-6
while offset!=0:
    print("connecting...")
    if offset>0:
        offset=offset-1
    else:
        offset=offset+1
    print(offset)

connecting...
-5
connecting...
-4
connecting...
-3
connecting...
-2
connecting...
-1
connecting...
0


In [5]:
europe={
    'spain':'madrid',
    'france':'paris',
    'germany':'berlin',
    'norway':'olso'
}
for key,value in europe.items():
    print(f"The capital of {key.title()} is {value.title()}")

The capital of Spain is Madrid
The capital of France is Paris
The capital of Germany is Berlin
The capital of Norway is Olso


In [2]:
import numpy as np
np_height=np.array([4.67,5.66,2.34,5.34,7.65])
np_weight=np.array([65.4,59.3,44.56,78.9,65.89])
np_person=np.column_stack((np_height,np_weight))
np_bmi=np.array([np_height,np_weight])
np_person
np_bmi

array([[ 4.67,  5.66,  2.34,  5.34,  7.65],
       [65.4 , 59.3 , 44.56, 78.9 , 65.89]])

In [4]:

np_bmi[:,3] #all row of that column

array([ 5.34, 78.9 ])

In [13]:
np_person[3][1] #row and colum

78.9

In [12]:
np_person[:,0] #all row of that column

array([4.67, 5.66, 2.34, 5.34, 7.65])

In [14]:
np_person

array([[ 4.67, 65.4 ],
       [ 5.66, 59.3 ],
       [ 2.34, 44.56],
       [ 5.34, 78.9 ],
       [ 7.65, 65.89]])

In [7]:
for height in np_height:
    print(height)
np_bmi

4.67
5.66
2.34
5.34
7.65


array([[ 4.67,  5.66,  2.34,  5.34,  7.65],
       [65.4 , 59.3 , 44.56, 78.9 , 65.89]])

In [8]:
for val in np_bmi:
    print(val)

[4.67 5.66 2.34 5.34 7.65]
[65.4  59.3  44.56 78.9  65.89]


In [21]:
for val in np_person:
    print(val)

[ 4.67 65.4 ]
[ 5.66 59.3 ]
[ 2.34 44.56]
[ 5.34 78.9 ]
[ 7.65 65.89]


In [12]:
#TO get every element of a numpy array

#column stack >>> height, weight, height, weight
for val in np.nditer(np_person):
    print(val)

4.67
65.4
5.66
59.3
2.34
44.56
5.34
78.9
7.65
65.89


In [9]:
#row stack >>>only height and then only weight
for val in np.nditer(np_bmi):
    print(val)
np_bmi

4.67
5.66
2.34
5.34
7.65
65.4
59.3
44.56
78.9
65.89


array([[ 4.67,  5.66,  2.34,  5.34,  7.65],
       [65.4 , 59.3 , 44.56, 78.9 , 65.89]])

In [2]:
import pandas as pd

brics=pd.read_csv("brics.csv",index_col=0)
brics

country    capital   area  population
BR   Brazil   Brasilia   8.90       200.4
RU   Russia     Moscow  14.60       147.5
GR  Germany     Berlin   5.60        60.5
IN    India  New Delhi   5.46      1225.0
NW   Norway       Olso   5.67        80.6

In [15]:
for val in brics:
    print(val)

country
capital
area
population


In [16]:
for lab,row in brics.iterrows():
    print(lab)
    print(row)

BR
country         Brazil
capital       Brasilia
area               8.9
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            14.6
population     147.5
Name: RU, dtype: object
GR
country       Germany
capital        Berlin
area              5.6
population       60.5
Name: GR, dtype: object
IN
country           India
capital       New Delhi
area               5.46
population       1225.0
Name: IN, dtype: object
NW
country       Norway
capital         Olso
area            5.67
population      80.6
Name: NW, dtype: object


In [8]:
#only country name
for lab,row in brics.iterrows():
    print(lab+":"+ str(row['area']>6))
    


BR:True
RU:True
GR:False
IN:False
NW:False


In [34]:
"""for lab,row in brics.iterrows():
    #brics.iloc[:,4]=len(row[0])
#brics
"""

'for lab,row in brics.iterrows():\n    #brics.iloc[:,4]=len(row[0])\n#brics\n'

In [5]:
#apply function to add new column
brics['name_length']=brics['country'].apply(len)
brics

country    capital   area  population  name_length
BR   Brazil   Brasilia   8.90       200.4            6
RU   Russia     Moscow  14.60       147.5            6
GR  Germany     Berlin   5.60        60.5            7
IN    India  New Delhi   5.46      1225.0            5
NW   Norway       Olso   5.67        80.6            6

In [3]:
for lab,row in brics.iterrows():
    brics.loc[lab,'COUNTRY']=row['country'].upper()
brics

country    capital   area  population  COUNTRY
BR   Brazil   Brasilia   8.90       200.4   BRAZIL
RU   Russia     Moscow  14.60       147.5   RUSSIA
GR  Germany     Berlin   5.60        60.5  GERMANY
IN    India  New Delhi   5.46      1225.0    INDIA
NW   Norway       Olso   5.67        80.6   NORWAY

In [6]:
for lab,row in brics.iterrows():
    brics.loc[lab,'CAPITAL']=row['capital'].apply(str.upper())
brics

AttributeError: 'str' object has no attribute 'apply'

In [7]:
brics['CAPITAL']=brics['capital'].apply(lambda x:x.upper())
# or

#brics['CAPITAL']=brics['capital'].apply(str.upper)
brics

country    capital   area  population  name_length  COUNTRY    CAPITAL
BR   Brazil   Brasilia   8.90       200.4            6   BRAZIL   BRASILIA
RU   Russia     Moscow  14.60       147.5            6   RUSSIA     MOSCOW
GR  Germany     Berlin   5.60        60.5            7  GERMANY     BERLIN
IN    India  New Delhi   5.46      1225.0            5    INDIA  NEW DELHI
NW   Norway       Olso   5.67        80.6            6   NORWAY       OLSO

In [8]:
brics['capital_with_y']=brics['CAPITAL'].apply(lambda x:x.replace("I","Y"))
brics

country    capital   area  population  name_length  COUNTRY    CAPITAL  \
BR   Brazil   Brasilia   8.90       200.4            6   BRAZIL   BRASILIA   
RU   Russia     Moscow  14.60       147.5            6   RUSSIA     MOSCOW   
GR  Germany     Berlin   5.60        60.5            7  GERMANY     BERLIN   
IN    India  New Delhi   5.46      1225.0            5    INDIA  NEW DELHI   
NW   Norway       Olso   5.67        80.6            6   NORWAY       OLSO   

   capital_with_y  
BR       BRASYLYA  
RU         MOSCOW  
GR         BERLYN  
IN      NEW DELHY  
NW           OLSO

In [9]:
for lab,row in brics.iterrows():
    brics.loc[lab,'lower_country']=row['country'].lower()
brics

country    capital   area  population  name_length  COUNTRY    CAPITAL  \
BR   Brazil   Brasilia   8.90       200.4            6   BRAZIL   BRASILIA   
RU   Russia     Moscow  14.60       147.5            6   RUSSIA     MOSCOW   
GR  Germany     Berlin   5.60        60.5            7  GERMANY     BERLIN   
IN    India  New Delhi   5.46      1225.0            5    INDIA  NEW DELHI   
NW   Norway       Olso   5.67        80.6            6   NORWAY       OLSO   

   capital_with_y lower_country  
BR       BRASYLYA        brazil  
RU         MOSCOW        russia  
GR         BERLYN       germany  
IN      NEW DELHY         india  
NW           OLSO        norway

In [10]:
brics['Count-a']=brics['capital'].apply(lambda x : x.count('a'))
brics

country    capital   area  population  name_length  COUNTRY    CAPITAL  \
BR   Brazil   Brasilia   8.90       200.4            6   BRAZIL   BRASILIA   
RU   Russia     Moscow  14.60       147.5            6   RUSSIA     MOSCOW   
GR  Germany     Berlin   5.60        60.5            7  GERMANY     BERLIN   
IN    India  New Delhi   5.46      1225.0            5    INDIA  NEW DELHI   
NW   Norway       Olso   5.67        80.6            6   NORWAY       OLSO   

   capital_with_y lower_country  Count-a  
BR       BRASYLYA        brazil        2  
RU         MOSCOW        russia        0  
GR         BERLYN       germany        0  
IN      NEW DELHY         india        0  
NW           OLSO        norway        0

In [13]:
brics['Greater-6']=brics['area'].apply(lambda x:x if x>6 else 0 )
brics

country    capital   area  population  name_length  COUNTRY    CAPITAL  \
BR   Brazil   Brasilia   8.90       200.4            6   BRAZIL   BRASILIA   
RU   Russia     Moscow  14.60       147.5            6   RUSSIA     MOSCOW   
GR  Germany     Berlin   5.60        60.5            7  GERMANY     BERLIN   
IN    India  New Delhi   5.46      1225.0            5    INDIA  NEW DELHI   
NW   Norway       Olso   5.67        80.6            6   NORWAY       OLSO   

   capital_with_y lower_country  Count-a  Greater-6  
BR       BRASYLYA        brazil        2        8.9  
RU         MOSCOW        russia        0       14.6  
GR         BERLYN       germany        0        0.0  
IN      NEW DELHY         india        0        0.0  
NW           OLSO        norway        0        0.0

In [15]:
for lab,row in brics.iterrows():
    brics.loc[lab,'Count_s']=row['capital'].count('s')
brics['Count_i']=brics['capital'].apply(lambda x: x.count('s'))
brics

country    capital   area  population  name_length  COUNTRY    CAPITAL  \
BR   Brazil   Brasilia   8.90       200.4            6   BRAZIL   BRASILIA   
RU   Russia     Moscow  14.60       147.5            6   RUSSIA     MOSCOW   
GR  Germany     Berlin   5.60        60.5            7  GERMANY     BERLIN   
IN    India  New Delhi   5.46      1225.0            5    INDIA  NEW DELHI   
NW   Norway       Olso   5.67        80.6            6   NORWAY       OLSO   

   capital_with_y lower_country  Count-a  Greater-6  Count_s  Count_i  
BR       BRASYLYA        brazil        2        8.9      1.0        1  
RU         MOSCOW        russia        0       14.6      1.0        1  
GR         BERLYN       germany        0        0.0      0.0        0  
IN      NEW DELHY         india        0        0.0      0.0        0  
NW           OLSO        norway        0        0.0      1.0        1

In [9]:
for lab,row in brics.iterrows():
    
    brics.loc[lab,"new_col"]=row['population']-10
brics

country    capital   area  population  new_col
BR   Brazil   Brasilia   8.90       200.4    190.4
RU   Russia     Moscow  14.60       147.5    137.5
GR  Germany     Berlin   5.60        60.5     50.5
IN    India  New Delhi   5.46      1225.0   1215.0
NW   Norway       Olso   5.67        80.6     70.6

In [11]:
brics['new_col2']=brics['area'].apply(lambda x: x*2)
brics

country    capital   area  population  new_col  new_col2
BR   Brazil   Brasilia   8.90       200.4    190.4     17.80
RU   Russia     Moscow  14.60       147.5    137.5     29.20
GR  Germany     Berlin   5.60        60.5     50.5     11.20
IN    India  New Delhi   5.46      1225.0   1215.0     10.92
NW   Norway       Olso   5.67        80.6     70.6     11.34